### ISSUE TITLE
Sometimes, exit file is written late

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pypeFLOW#23]
```
pwatcher.fs_based - DEBUG - Status EXIT 0 for heartbeat:heartbeat-J75fc47f525b4da4c2f26b876613517ecd4ecee362572f2eaf391cdec58e4579b
```
But sometimes we see
```
pwatcher.fs_based - DEBUG - Status EXIT  for heartbeat:heartbeat-Jf5e95c43e2eaec88a3616083cac729abc967efb72b38bd78adce8e88a8d6453e
```
Missing `0` after `EXIT`. We then get an exception,
```
Exception: Caused by:
Traceback (most recent call last):
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 657, in _refreshTargets
    numAliveThreads = self.thread_handler.alive(task2thread.values())
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_bridge.py", line 197, in alive
    fred.endrun(status)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_bridge.py", line 83, in endrun
    code = int(status.split()[1])
IndexError: list index out of range
```
That's because we split `EXIT 0` to learn the exit-code. Apparently, pwatcher is reading the exit file before the exit code has been written to it. (The exit file contains the expected `0` when I view it now.)
```js
pypeflow.pwatcher_bridge - DEBUG - In alive(), updated result of query:{'jobids': {
  'J5d1ec9ee6da2fafc1dfc7bbaa84a8a1df8aa588423fbea1acdf8a960653f7f6f':
    'RUNNING',
  'Jf5e95c43e2eaec88a3616083cac729abc967efb72b38bd78adce8e88a8d6453e':
    'EXIT ',
  'Jf38d0c8a5aed4a499e1976659c2546d2044913288c65af093e6b213dd11351a6':
    'RUNNING'
}}
```
We could prevent that by writing to a different file, and then performing an atomic `mv` operation. Alternatively, pwatcher could just wait a few seconds and retry.

**Comment by pb-cdunn** [comment]
For now, the simple work-around is to delete `mypwatcher/` and re-run. But I'll address this soon.
