### ISSUE TITLE
`isSatisfied()` needs to wait and re-try on missing outputs.

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pypeFLOW#26]
```
Traceback (most recent call last):
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/pi/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/pi/pypeFLOW/pypeflow/controller.py", line 637, in _refreshTargets
    if not (set(prereqJobURLs) & updatedTaskURLs) and taskObj.isSatisfied():
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/pi/pypeFLOW/pypeflow/task.py", line 149, in isSatisfied
    return not self._getRunFlag()
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/pi/pypeFLOW/pypeflow/task.py", line 143, in _getRunFlag
    return any( [ f(self.inputDataObjs, self.outputDataObjs, self.parameters) for f in self._compareFunctions] )
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/pi/pypeFLOW/pypeflow/task.py", line 854, in timeStampCompare
    inputDataObjsTS.append((f.timeStamp, 'A', f))
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/pi/pypeFLOW/pypeflow/data.py", line 115, in timeStamp
    raise FileNotExistError("No such file:%r on %r" % (self.localFileName, platform.node()) )
FileNotExistError: "No such file:'/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/siv/testkit-jobs/sa3_pipelines/hgap5_fake/synth5k/job_output/tasks/falcon_ns.tasks.task_hgap_run-0/run-fasta2referenceset/asm.referenceset.xml' on 'vm1004-def14'"
```
But that file *does* exist!

**Comment by pb-cdunn** [comment]
Jason, this is not urgent. Let's talk about this after you finish the paper.

For now, I might add a sleep+retry as a quick fix.

**Comment by pb-jchin** [comment]
ok. thanks.
