### ISSUE TITLE
Heartbeat files not being created

### ISSUE THREAD

**Issue by bredelings** [PacificBiosciences/pypeFLOW#41]
While running the synth0 test under SLURM, I get a lot of messages like this:

`2016-11-23 17:51:03,872 - pwatcher.fs_based - DEBUG - Unable to remove heartbeat '/home/bredelings/pacbio/FALCON-integrate/FALCON-examples/run/synth0/mypwatcher/heartbeats/hea
Traceback (most recent call last):
  File "/home/bredelings/pacbio/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 553, in get_status
    os.remove(heartbeat_path)
OSError: [Errno 2] No such file or directory: '/home/bredelings/pacbio/FALCON-integrate/FALCON-examples/run/synth0/mypwatcher/heartbeats/heartbeat-Pdc6b30580a8be9'
`

Also, I see a lot of lines like this:
[INFO]sleep 0.7s
And there is almost no cpu usage.

**Comment by pb-cdunn** [comment]
Ignore the heartbeat warnings. That relates to either quickness or filesystem latency and will be turned off soon.

The Slurm problem is almost certainly #40.

**Comment by bredelings** [comment]
I'm running this on a single box that is both head and worker, so there shouldn't be filesystem delay.

I guess I was assuming that the heartbeat thing was the reason the SLURM run took so much longer than the "local" run for synth0, and the CPU usage was so low.  But maybe that is a separate issue.

**Comment by ADSakura** [comment]
Have you solved this issue? I meet the same problem, and the  Heartbeat files are not being created.

**Comment by suvi93** [comment]
I'm still getting the error.

2019-02-19 08:11:58,284 - pwatcher.fs_based:600 - ERROR - Failed to kill job for heartbeat 'heartbeat-Pd905dffe513485' (which might mean it was already gone): IOError(2, 'No such file or directory')
Traceback (most recent call last):
File "/home/ssubha/software/falcon/falcon-2018.31.08-03.06/lib/python2.7/site-packages/pwatcher/fs_based.py", line 597, in delete_heartbeat
bjob.kill(state, heartbeat)
File "/home/ssubha/software/falcon/falcon-2018.31.08-03.06/lib/python2.7/site-packages/pwatcher/fs_based.py", line 272, in kill
with open(heartbeat_fn) as ifs:
IOError: [Errno 2] No such file or directory: '/home/ssubha/Suvratha/mosquito/pacbiodata/falcon/mypwatcher/heartbeats/heartbeat-Pd905dffe513485'
2019-02-19 08:11:58,285 - pwatcher.fs_based:607 - DEBUG - Cannot remove heartbeat '/home/ssubha/Suvratha/mosquito/pacbiodata/falcon/mypwatcher/heartbeats/heartbeat-Pd905dffe513485': OSError(2, 'No such file or directory')

**Comment by pb-cdunn** [comment]
Please use `pwatcher_type = blocking`. The `fs_based` process-watcher is too hard to maintain.

Also, `DEBUG` means that this is not an error. (The OSError is trapped and logged.) To learn your actual error, look for `stderr` for the run-directory of the task that is failing.
