### ISSUE TITLE
Problem with HPC pro and Falcon

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/pypeFLOW#53]
Hi,
I have got the following error with ` install_unzip_180312.sh`:
```
[5711]$(u'lfs setstripe -c 12 /lustre/scratch/waterhouse_team/benth/falcon')
[5711]Call u'lfs setstripe -c 12 /lustre/scratch/waterhouse_team/benth/falcon' returned 0.
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run.cfg
[ERROR]Failed to parse config "fc_run.cfg".
Traceback (most recent call last):
  File "/lustre/work-lustre/waterhouse_team/apps/falcon_unzip/fc_env_180905/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 136, in main1
    support.parse_config(input_config_fn))
  File "/lustre/work-lustre/waterhouse_team/apps/falcon_unzip/fc_env_180905/lib/python2.7/site-packages/falcon_kit/run_support.py", line 167, in get_dict_from_old_falcon_cfg
    sge_option = config.get(section, 'sge_option_da')
  File "/work/waterhouse_team/miniconda2/envs/falcon_unzip/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option u'sge_option_da' in section: u'General'
Traceback (most recent call last):
  File "/lustre/work-lustre/waterhouse_team/apps/falcon_unzip/fc_env_180905/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.0+git.6bb3daa96931aece9bd3742bccc77ad257b7bb65', 'console_scripts', 'fc_run')()
  File "/lustre/work-lustre/waterhouse_team/apps/falcon_unzip/fc_env_180905/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 644, in main
    main1(argv[0], args.config, args.logger)
  File "/lustre/work-lustre/waterhouse_team/apps/falcon_unzip/fc_env_180905/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 136, in main1
    support.parse_config(input_config_fn))
  File "/lustre/work-lustre/waterhouse_team/apps/falcon_unzip/fc_env_180905/lib/python2.7/site-packages/falcon_kit/run_support.py", line 167, in get_dict_from_old_falcon_cfg
    sge_option = config.get(section, 'sge_option_da')
  File "/work/waterhouse_team/miniconda2/envs/falcon_unzip/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option u'sge_option_da' in section: u'General'
```

with the following cfg file:
```
[General]
input_fofn = ../fasta2DB_input.fofn
input_type = raw

seed_coverage = 40 #(for Banana Diploid) and 40 (for Nbenth)
genome_size = 320000000 #(for Banana Diploid) and 320000000 (for Nbenth)

length_cutoff = -1
length_cutoff_pr = -1

job_type = string
pwatcher_type = blocking
job_queue = qsub -S /bin/bash -V -q lyra -N ${JOB_ID} -o "${STDOUT_FILE}" -e "${STDERR_FILE}" -l nodes=1:ppn=${NPROC},mem=25gb -W umask=0007,block=true "${CMD}"

pa_concurrent_jobs = 96
cns_concurrent_jobs = 96
ovlp_concurrent_jobs = 96

pa_HPCdaligner_option =  -v -B128 -M32 -e.70 -l4800 -s100 -k18 -h480 -w8 
ovlp_HPCdaligner_option = -v -B128 -M32 -h1024 -e.96 -l2400 -s100 -k18

pa_DBsplit_option = -a -x500 -s200
ovlp_DBsplit_option = -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 2 --max_n_read 100 --n_core 8
falcon_sense_skip_contained = True

overlap_filtering_setting = --max_diff 80 --max_cov 80 --min_cov 2 --n_core 12
```

How would I convert sge to HPC pro?

Thank you in advance.

Michal

**Comment by mictadlo** [comment]
Is this [bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pb-falcon/meta.yaml) the same to your recommended version?

Thank you in advance,

Michal

**Comment by pb-cdunn** [comment]
`pb-falcon` has the Python code, `pb-assembly` pulls that along with all dependencies.
