### ISSUE TITLE
PBS needs jobid for qdel

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pypeFLOW#54]
https://github.com/PacificBiosciences/FALCON/issues/507

@yingzhang121 wrote:

> I tried the setting of kill string, but it didn't work.
In PBS system, it is easy to get the job id. You can use ${PBS_JOBID}, or more simple, if you define, submit=$(qsub -S /bin/bash script.sh), the value of submit is actually the job id, and you can run "qdel ${submit}.

> In my PBS, there is even not -W block=T option

**Comment by pb-cdunn** [comment]
It sounds like you cannot use `blocking` mode, so you need `fs_based` to pass the actual, generated job-id to `qdel`. Let me see ...

**Comment by pb-cdunn** [comment]
Can you tell us *exactly* all the output from `qsub` on your system?

We will try to parse that, and if parsing fails we will fall-back on JOB_NAME, to preserve current behavior for others.

Will you be able to test this if I push to a branch?

**Comment by pb-cdunn** [comment]
(For us, locally: http://bitbucket.nanofluidics.com:7990/projects/SAT/repos/pypeflow/pull-requests/51/overview )

**Comment by pb-cdunn** [comment]
If possible, try the branch called `feature/TAG-3043-pbs-qdel`.

**Comment by baozg** [comment]
Hi, @pb-cdunn , I try the branch called `feature/TAG-3043-pbs-qdel.`, but it also raise same error.

```bash
[ERROR]Task Node(0-rawreads/build) failed with exit-code=99
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/build)])                                                                          
[ERROR]ready: set([])
        submitted: set([])
[INFO]CALL:
 qdel -j P43deb85ec32a54
qdel: invalid option -- 'j'
usage: qdel [{ -a | -c | -p | -t | -W delay | -m message}] [<JOBID>[<JOBID>]|'all'|'ALL']...                                                                  
       -a -c, -m, -p, -t, and -W are mutually exclusive
Traceback (most recent call last):
  File "/data/software/Anaconda3/envs/denovo_asm/bin/fc_run", line 11, in <module>                                                                            
    load_entry_point('falcon-kit==1.2.4', 'console_scripts', 'fc_run')()
  File "/data/software/Anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 726, in main                                     
    main1(argv[0], args.config, args.logger)
  File "/data/software/Anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 76, in main1                                     
    input_fofn_fn=input_fofn_fn,
  File "/data/software/Anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 242, in run                                      
    dist=Dist(NPROC=4, MB=4000, job_dict=config['job.step.da']),
  File "/data/software/Anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/pype.py", line 106, in gen_parallel_tasks                             
    wf.refreshTargets()
  File "/data/software/Anaconda3/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets                 
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/data/software/Anaconda3/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets                
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads/build)])
```

Here is my config:

```bash
[job.defaults]                                                                                                                                             
 JOB_QUEUE=all                                                                                                                                              
MB=32768                                                                                                                                                   
NPROC=6                                                                                                                                                    
njobs=32                                                                                                                                                   

submit = qsub -V \                                                                                                                                        
-q ${JOB_QUEUE}     \                                                                                                                                    
-N ${JOB_NAME}      \                                                                                                                                    
-o "${JOB_STDOUT}"  \                                                                                                                                    
-e "${JOB_STDERR}"  \                                                                                                                                    
-l nodes=1:ppn=${NPROC},mem=${MB}M    \                                                                                                                  "${JOB_SCRIPT}"                                                                                                                                          
                                                                                                                         
kill = qdel -j ${JOB_NAME}

[General]
job_type=pbs
pwatcher_type= fs_based
```

**Comment by pb-cdunn** [comment]
```
 qdel -j P43deb85ec32a54
qdel: invalid option -- 'j'
usage: qdel [{ -a | -c | -p | -t | -W delay | -m message}] [<JOBID>[<JOBID>]|'all'|'ALL']...                                                                  
       -a -c, -m, -p, -t, and -W are mutually exclusive
```
But that came from *your* kill-command:
```ini
[job.defaults]

submit = qsub -V \                                                                                                                                        
-q ${JOB_QUEUE}     \                                                                                                                                    
-N ${JOB_NAME}      \                                                                                                                                    
-o "${JOB_STDOUT}"  \                                                                                                                                    
-e "${JOB_STDERR}"  \                                                                                                                                    
-l nodes=1:ppn=${NPROC},mem=${MB}M    \                                                                                                                  "${JOB_SCRIPT}"                                                                                                                                          
                                                                                                                         
kill = qdel -j ${JOB_NAME}
```
Maybe drop `-j`? Doesn't seem like something we can solve here.
